# Generated by Django 3.0.14 on 2022-10-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('measure', models.CharField(choices=[('grams', 'Grams'), ('lbs', 'Pounds'), ('kilograms', 'Kilograms')], default='grams', max_length=9)),
                ('nutrient', models.CharField(choices=[('sugar', 'sugar_g'), ('fiber', 'fiber_g'), ('serving_size', 'serving_size_g'), ('sodium', 'sodium_mg'), ('name', 'name'), ('potassium', 'potassium_mg'), ('fat_saturated', 'fat_saturated_g'), ('fat_total', 'fat_total_g'), ('calories', 'calories'), ('cholesterol', 'cholesterol_mg'), ('carbohydrates_total', 'carbohydrates_total_g')], default='sugar', max_length=21)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
