# Generated by Django 3.0.14 on 2022-10-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates_total_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol_mg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_saturated_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_total_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium_mg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_size_g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium_mg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar_g',
            field=models.IntegerField(null=True),
        ),
    ]
