# Generated by Django 3.0.14 on 2022-10-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
