# Generated by Django 3.0.14 on 2022-10-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221013_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
