# Generated by Django 3.0.14 on 2022-10-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221013_1658'),
        ('home', '0003_auto_20221013_1612'),
    ]

    operations = [
    ]
