# Generated by Django 3.0.14 on 2022-10-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20221013_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='nutrient',
            field=models.CharField(choices=[('calories', 'calories'), ('protein', 'protein_g')], default='calories', max_length=21),
        ),
    ]
