# Generated by Django 3.0.14 on 2022-10-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221013_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.FloatField(default=0, null=True),
        ),
    ]
