# Generated by Django 3.0.14 on 2022-10-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221013_2000'),
        ('home', '0004_merge_20221013_2010'),
    ]

    operations = [
    ]
