# Generated by Django 3.0.14 on 2022-10-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20221013_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
    ]
